// flow-typed signature: acf0c21ec6268f38d5a99297348cba1d
// flow-typed version: <<STUB>>/redom_v3.14.2/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redom/bench/bench-notifyDown' {
  declare module.exports: any;
}

declare module 'redom/bench/bench' {
  declare module.exports: any;
}

declare module 'redom/bench/index' {
  declare module.exports: any;
}

declare module 'redom/bench/redom-notifyDown' {
  declare module.exports: any;
}

declare module 'redom/bench/redom' {
  declare module.exports: any;
}

declare module 'redom/build-doc' {
  declare module.exports: any;
}

declare module 'redom/dist/documentation/main' {
  declare module.exports: any;
}

declare module 'redom/dist/prism' {
  declare module.exports: any;
}

declare module 'redom/dist/redom.es' {
  declare module.exports: any;
}

declare module 'redom/dist/redom.es.min' {
  declare module.exports: any;
}

declare module 'redom/dist/redom' {
  declare module.exports: any;
}

declare module 'redom/dist/redom.min' {
  declare module.exports: any;
}

declare module 'redom/esm/create-element' {
  declare module.exports: any;
}

declare module 'redom/esm/html' {
  declare module.exports: any;
}

declare module 'redom/esm/index' {
  declare module.exports: any;
}

declare module 'redom/esm/list' {
  declare module.exports: any;
}

declare module 'redom/esm/listpool' {
  declare module.exports: any;
}

declare module 'redom/esm/mount' {
  declare module.exports: any;
}

declare module 'redom/esm/parse-query' {
  declare module.exports: any;
}

declare module 'redom/esm/place' {
  declare module.exports: any;
}

declare module 'redom/esm/router' {
  declare module.exports: any;
}

declare module 'redom/esm/setattr' {
  declare module.exports: any;
}

declare module 'redom/esm/setchildren' {
  declare module.exports: any;
}

declare module 'redom/esm/setstyle' {
  declare module.exports: any;
}

declare module 'redom/esm/svg' {
  declare module.exports: any;
}

declare module 'redom/esm/text' {
  declare module.exports: any;
}

declare module 'redom/esm/unmount' {
  declare module.exports: any;
}

declare module 'redom/esm/util' {
  declare module.exports: any;
}

declare module 'redom/rollup.config' {
  declare module.exports: any;
}

declare module 'redom/test/index' {
  declare module.exports: any;
}

declare module 'redom/test/redom' {
  declare module.exports: any;
}

declare module 'redom/test/test' {
  declare module.exports: any;
}

declare module 'redom/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redom/bench/bench-notifyDown.js' {
  declare module.exports: $Exports<'redom/bench/bench-notifyDown'>;
}
declare module 'redom/bench/bench.js' {
  declare module.exports: $Exports<'redom/bench/bench'>;
}
declare module 'redom/bench/index.js' {
  declare module.exports: $Exports<'redom/bench/index'>;
}
declare module 'redom/bench/redom-notifyDown.js' {
  declare module.exports: $Exports<'redom/bench/redom-notifyDown'>;
}
declare module 'redom/bench/redom.js' {
  declare module.exports: $Exports<'redom/bench/redom'>;
}
declare module 'redom/build-doc.js' {
  declare module.exports: $Exports<'redom/build-doc'>;
}
declare module 'redom/dist/documentation/main.js' {
  declare module.exports: $Exports<'redom/dist/documentation/main'>;
}
declare module 'redom/dist/prism.js' {
  declare module.exports: $Exports<'redom/dist/prism'>;
}
declare module 'redom/dist/redom.es.js' {
  declare module.exports: $Exports<'redom/dist/redom.es'>;
}
declare module 'redom/dist/redom.es.min.js' {
  declare module.exports: $Exports<'redom/dist/redom.es.min'>;
}
declare module 'redom/dist/redom.js' {
  declare module.exports: $Exports<'redom/dist/redom'>;
}
declare module 'redom/dist/redom.min.js' {
  declare module.exports: $Exports<'redom/dist/redom.min'>;
}
declare module 'redom/esm/create-element.js' {
  declare module.exports: $Exports<'redom/esm/create-element'>;
}
declare module 'redom/esm/html.js' {
  declare module.exports: $Exports<'redom/esm/html'>;
}
declare module 'redom/esm/index.js' {
  declare module.exports: $Exports<'redom/esm/index'>;
}
declare module 'redom/esm/list.js' {
  declare module.exports: $Exports<'redom/esm/list'>;
}
declare module 'redom/esm/listpool.js' {
  declare module.exports: $Exports<'redom/esm/listpool'>;
}
declare module 'redom/esm/mount.js' {
  declare module.exports: $Exports<'redom/esm/mount'>;
}
declare module 'redom/esm/parse-query.js' {
  declare module.exports: $Exports<'redom/esm/parse-query'>;
}
declare module 'redom/esm/place.js' {
  declare module.exports: $Exports<'redom/esm/place'>;
}
declare module 'redom/esm/router.js' {
  declare module.exports: $Exports<'redom/esm/router'>;
}
declare module 'redom/esm/setattr.js' {
  declare module.exports: $Exports<'redom/esm/setattr'>;
}
declare module 'redom/esm/setchildren.js' {
  declare module.exports: $Exports<'redom/esm/setchildren'>;
}
declare module 'redom/esm/setstyle.js' {
  declare module.exports: $Exports<'redom/esm/setstyle'>;
}
declare module 'redom/esm/svg.js' {
  declare module.exports: $Exports<'redom/esm/svg'>;
}
declare module 'redom/esm/text.js' {
  declare module.exports: $Exports<'redom/esm/text'>;
}
declare module 'redom/esm/unmount.js' {
  declare module.exports: $Exports<'redom/esm/unmount'>;
}
declare module 'redom/esm/util.js' {
  declare module.exports: $Exports<'redom/esm/util'>;
}
declare module 'redom/rollup.config.js' {
  declare module.exports: $Exports<'redom/rollup.config'>;
}
declare module 'redom/test/index.js' {
  declare module.exports: $Exports<'redom/test/index'>;
}
declare module 'redom/test/redom.js' {
  declare module.exports: $Exports<'redom/test/redom'>;
}
declare module 'redom/test/test.js' {
  declare module.exports: $Exports<'redom/test/test'>;
}
declare module 'redom/watch.js' {
  declare module.exports: $Exports<'redom/watch'>;
}
